include /home/pi/devel/OpenNI2/ThirdParty/PSCommon/BuildSystem/CommonDefs.mak

BIN_DIR = ..//Bin

INC_DIRS = \
	/home/pi/devel/OpenNI2/Include \
	/home/pi/devel/OpenNI2/Samples/Common

SRC_FILES = *.cpp

USED_LIBS += OpenNI2

EXE_NAME = SimpleRead

CFLAGS += -Wall

include /home/pi/devel/OpenNI2/ThirdParty/PSCommon/BuildSystem/CommonCppMakefile
